- name: Playbook for play level variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Printing play level variables
      ansible.builtin.debug:
        msg:  "{{ URL }}"

- name: Play for task level variables
  hosts: all
  tasks:
    - name: Printing tasks level variables
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: "{{ URL }}"
