- name: Play for task level variables
  hosts: all
  tasks:
    - name: Printing tasks level variables
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: "{{ URL }}"

- name: Play for files vars
  hosts: all
  vars_files:
    - var.yml
  tasks:
    - name: printing vars from file
      ansible.builtin.debug:
        msg: "{{ URL }}"

- name: Play for inventory vars
  hosts: all
  tasks:
    - name: Printing inventory variables
      ansible.builtin.debug:
        msg: " {{ URL }}"
