-  name: Play for ansible facts
   hosts: localhost
   tasks:
     - name: task for ansible facts
       ansible.builtin.debug:
         msg: "{{ ansible_fqdn }}"

- name: Play for storing task output
  hosts: localhost
  tasks:
    - name: task for storing Uptime
      ansible.builtin.shell: uptime
      register: out
    - name: task to print out
      ansible.builtin.debug:
        msg: "{{ out }}"
    - name: task for standard variable
      ansible.builtin.set_fact:
        stat = "{{ out.rc }}"
    - name: print stat
      ansible.builtin.debug:
        msg: " {{ stat }}"

