- name: loop in ansible
  hosts: localhost
  tasks:
   - name: loop
     debug:
      msg: Fruit Name - {{ item }}
     loop:
       - Apple
       - Banana
       - Orange
       - Pinaple
   - name: loop with item
     debug:
       msg: Fruit name - {{ item.name}} , Quantity - {{ item.Quantity }}
     loop:
      - {name: "Apple", Quantity: 10 }
      - {name: "Banana", Quantity: 20 }
      - {name: "Orange", Quantity: 30 }